name: morning
on:
  schedule:
  - cron:  '0 21 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID_CS: ${{ secrets.APP_ID_CS }}
      APP_SECRET_CS: ${{ secrets.APP_SECRET_CS }}
      TEMPLATE_ID_CS: ${{ secrets.TEMPLATE_ID_CS }}
      USER_ID_CS: ${{ secrets.USER_ID_CS }}
      START_DATE_CS: ${{ secrets.START_DATE_CS }}
      BIRTHDAY_CS: ${{ secrets.BIRTHDAY_CS }}
      CITY_CS: ${{ secrets.CITY_CS }}
